### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [opensass/tripper#4]
- [ ] mv jwt_storage middlware
- [ ] More DRY
- [ ] Decouple Prompts Static data from functions
- [ ] Document Core Functionalities
- [ ] Fix Lighthouse Scores
- [ ] Stream messages from `aws_sdk_bedrockruntime` instead of waiting for the whole response.
- [ ] Wire up Stripe
- [ ] Profile Page
- [ ] mv theme_signal theme_hook
- [x] Google Maps
- [x] Fix Deployment
